# Test and build toml-patch
trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run typecheck
    npm test
    npm run specs
    npm run build
  displayName: 'Install, typecheck, test, validate, and build toml-patch'
