name: Test and Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm install
      env:
        CI: true
    - name: Typecheck
      run: npm run typecheck
    - name: Test
      run: npm test
    - name: Specs
      run: npm run specs
    - name: Build
      run: npm run build
    - name: Benchmark
      run: npm run benchmark -- --example
